### ISSUE TITLE
How does this connect to correct vantage account

### ISSUE THREAD

**Issue by wshelley** [vantage-sh/terraform-aws-vantage-integration#14]
I'm just looking at this project and I'm slightly confused at how this connects to the correct vantage account. Other integration methods use a set of paramaters (e.g. VantageID, VantageHandshakeID).

From what I understand this project creates the resources but doesn't connect it to vantage?

Any pointers appreciated.

**Comment by brookemckim** [comment]
hi @wshelley this is done via the API token which is supplied.

**Comment by wshelley** [comment]
hi @brookemckim - Could you please point me to the documentation or section of code where you can supply the API token to the "terraform-aws-vantage-integration"?
