### ISSUE TITLE
Allow customers to disable Autopilot in vantage/terraform-aws-vantage-integration module

### ISSUE THREAD

**Issue by SebRosander** [vantage-sh/terraform-aws-vantage-integration#2]
Currently, the `vantage/terraform-aws-vantage-integration` module enables Autopilot by default when creating an AWS infrastructure for Vantage. However, not all customers may want to use Autopilot for various reasons, including contractual or legal concerns, or a desire to follow the principle of least privilege.

The issue with enabling Autopilot by default is that it grants Vantage permissive permissions even if the customer chooses not to use Autopilot. This could potentially introduce security risks and violate compliance requirements.

Therefore, we propose adding an option to the module that allows customers to disable Autopilot when creating the AWS infrastructure for Vantage. This would give customers greater control over the permissions granted to Vantage and help them meet their security and compliance needs.

We suggest implementing this option as a boolean variable in the module's input variables, with the default value set to "true" (i.e., Autopilot enabled). Customers who wish to disable Autopilot could set this variable to "false" when calling the module.

We believe this change would make the `vantage/terraform-aws-vantage-integration` module more flexible and better aligned with customers' security and compliance requirements.

**Comment by SebRosander** [comment]
I tried to open a PR addressing this. Seems like you don't allow public PRs. 

```bash
git push
ERROR: Permission to vantage-sh/terraform-aws-vantage-integration.git denied to SebRosander.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Here are the code-snippets that could improve the current module: 
`main.tf`
```hcl
  dynamic "inline_policy" {
    for_each = var.enable_autopilot == true ? [1] : []
    content {
        name   = "VantageAutoPilot"
        policy = data.vantage_aws_provider_info.default.autopilot_policy
    }
  }
```

`variables.tf`
```hcl
variable "enable_autopilot" {
  type        = bool
  description = "Enable Vantage Autopilot. This will create more permissions for the cross account role."
  default     = true
}
```

**Comment by macb** [comment]
Hey @SebRosander, thanks for the report. Will apply your suggested changes and release a new version shortly.

In the future when contributing, you should be able to fork the repository, push your changes to your fork, and open a pull request from your fork against this repository.

**Comment by SebRosander** [comment]
Hey @macb 👋
Thanks for getting back and addressing my request! 

Would be good to get a section for contribution in the README for more people to follow in the future 👍 For now I'm happy to understand the flow and will pass it back in my org if needed.

Thanks!

**Comment by macb** [comment]
Yep, will add a contributing section.

This change is in the latest release and available via the terraform registry now.
