### ISSUE TITLE
Essential Eight compliance.

### ISSUE THREAD

**Issue by gothrek22** [vantage-sh/terraform-aws-vantage-integration#5]
Hi,

according to AWS Config implementation of Essential Eight security requirements, it's considered insecure to use ` kms:*, kms:Decrypt, kms:ReEncrypt*.` actions in an inline policy.

Here's the rule description:
```Checks if the inline policies attached to your IAM users, roles, and groups do not allow blocked actions on all AWS KMS keys. The rule is NON_COMPLIANT if any blocked action is allowed on all AWS KMS keys in an inline policy.```

Please consider moving away from using inline policies for the roles in the module.

Cheers,
Tom

**Comment by macb** [comment]
Thanks for the report @gothrek22. To be clear, we do not include `kms:*`, `kms:Decrypt` or `kms:ReEncrypt*` permissions in any policies, just `kms:List*` and `kms:Describe*` which allows for retrieving metadata but not using those keys for any encrypt/decrypt actions.
